---
title : "Limitations of composability of cis-regulatory elements in messenger RNA"
output: 
  bookdown::pdf_book:
    includes:
      in_header: authors.tex
    template: "./formatting/NAR-sample.tex"
    toc: false
    keep_tex : true
    pandoc_args: [ "--csl", "./references/nucleic-acids-research.csl" ]
    extra_dependencies: ["flafter", "placeins"]
bibliography: "./references/chimeraProject_no_url.bib"
---

\rhead{\scshape Composability in mRNA - preprint - \today}

```{r, echo = FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(bookdown)
```

\begin{abstract}

Genes are commonly abstracted into a coding sequence and cis-regulatory elements (CREs), that act together to regulate gene expression. 
A working model across synthetic and computational biology treats multiple CREs as composable, that is, having independent effects on gene expression.
The extent to which short CREs, i.e. sequence motifs, display context-dependence remains poorly understood, despite growing evidence of context-dependent effects from longer promoter and terminator regions.
We quantify the composability of CREs using combinatorial reporter genes in budding yeast, focusing on 3' terminators.
We find that the effect of a terminator on gene expression depends on promoter and coding sequence context.
We next estimate the effects of motifs within terminators by analysing transcriptome-wide datasets of mRNA decay with linear statistical models that assume composability.
We quantify the composability of combinations of motifs in multiple contexts.
The effect of a motif on RNA abundance depends on both the promoter and terminator context.
RNA-seq of 3' transcript ends shows that the polyadenylation site depends only on the terminator sequence and can be changed by motif insertion.
Our results emphasise the need for improved motif inference that includes context effects, which in turn could aid in the accurate engineering of synthetic genes.

\end{abstract}
